# Site settings
title: Alexander Qaddourah
description: CU Boulder Master's of Business Analytics Student
cover: assets/images/radhakrishna.jpg
logo: assets/images/logo.png
favicon: assets/images/favicon.png
baseurl: "/" # the subpath of your site, e.g. /blog/ or / for root
url: "https://alexqaddourah.github.io" # the base hostname & protocol for your site

pagination:

  # Site-wide kill switch, disabled here it doesn't run at all 
  enabled: true

  # Set to 'true' to enable pagination debugging. This can be enabled in the site config or only for individual pagination pages
  debug: false

  per_page: 5

# Social
twitter: alex_qaddourah
github:  alexqaddourah
linkedin: aqaddourah

#Additional Pages
about: about
contact: contact
privacy-policy: privacy-policy


permalink: /:title


# Google Analytics
analytics_id: ""

# Build settings
markdown: kramdown

kramdown:
  parse_block_html: true

plugins:
  - jekyll-paginate-v2


# Settings for rake task
safe: False
lsi: False
username: alexqaddourah #github username
repo: alexqaddourah.github.io #github repository
branch: master #branch
relative_source: ../websiteTheme/ #source directory
destination: ../websiteThemeQ #destination directory
production_url:  https://aqaddourah.com/
source_url:  https://github.com/aqaddourah/alexqaddourah.github.io #source repository url

exclude:
  - README.md
  - Rakefile
  - Gemfile
  - Gemfile.lock
  - changelog.md
  - "*.Rmd"
  - vendor
  - .travis.yml
