# Site settings
title: Alexander Qaddourah
description: CU Boulder Master's of Business Analytics Student
cover: assets/images/cu_boulder.jpg
logo:
favicon:
baseurl: "/" # the subpath of your site, e.g. /blog/ or / for root
url: "https://alexqaddourah.github.io" # the base hostname & protocol for your site

paginate: 5

# Social
twitter: alex_qaddourah
github:  alexqaddourah
linkedin: aqaddourah

#Additional Pages
about: about
contact: contact


permalink: /:title


# Google Analytics
analytics_id: ""

# Build settings
markdown: kramdown

kramdown:
  parse_block_html: true

plugins:
  - jekyll-paginate

exclude:
  - README.md
  - Rakefile
  - Gemfile
  - Gemfile.lock
  - changelog.md
  - "*.Rmd"
  - vendor
  - .travis.yml
