# Site settings
title: Rodrigo Medina
description: Estudiante Máster de Ingeniería Industrial - 
cover: assets/images/2018_cu_boulder_aerial.jpg
logo:
favicon:
baseurl: "/" # the subpath of your site, e.g. /blog/ or / for root
url: "https://diaz-de-vivar.github.io/" # the base hostname & protocol for your site

paginate: 5

# Social
twitter: AlonsoQuixada
github:  Diaz-De-Vivar
linkedin: aqaddourah

#Additional Pages
about: about
contact: contact


permalink: /:title


# Google Analytics
analytics_id: ""

# Build settings
markdown: kramdown

kramdown:
  parse_block_html: true

plugins:
  - jekyll-paginate

exclude:
  - README.md
  - Rakefile
  - Gemfile
  - Gemfile.lock
  - changelog.md
  - "*.Rmd"
  - vendor
  - .travis.yml
